sudo: required
dist: trusty
language: php

before_install:
  - sudo add-apt-repository -y ppa:scribus/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y xvfb scribus-ng



      
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start      
script:
  - sudo cp -R Grafik/Schriftarten /usr/share/fonts/truetype
  - sudo fc-cache -f -v
  - scribus-ng -v
  - scribus-ng -g -py .travis/to-pdf.py -pa verbose  -- Heft.sla    
  - sudo ls -l *.pdf
