sudo: required
dist: trusty
language: php
before_install:
- sudo add-apt-repository -y ppa:scribus/ppa
- sudo apt-get -qq update
- sudo apt-get install -y xvfb scribus-ng sshpass
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- sudo cp -R Grafik/Schriftarten /usr/share/fonts/truetype
- sudo fc-cache -f -v
- scribus-ng -g -py .travis/lehrerheft.py -pa verbose  -- Heft.sla
- mv Heft.pdf Lehrerheft-$TRAVIS_BRANCH-2.0.$TRAVIS_BUILD_NUMBER.pdf
- scribus-ng -g -py .travis/schuelerheft.py -pa verbose  -- Heft.sla
- mv Heft.pdf Schuelerheft-$TRAVIS_BRANCH-2.0.$TRAVIS_BUILD_NUMBER.pdf
after_success:
- echo -n $SSHKEY > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-keyscan $SSHHOST >> ~/.ssh/known_hosts
- sshpass -p $SSHPASS scp -v Schuelerheft-$TRAVIS_BRANCH-2.0.$TRAVIS_BUILD_NUMBER.pdf $SSHUSER@$SSHHOST:crosswalk/build/
- sshpass -p $SSHPASS scp -v Lehrerheft-$TRAVIS_BRANCH-2.0.$TRAVIS_BUILD_NUMBER.pdf $SSHUSER@$SSHHOST:crosswalk/build/
- sshpass -p $SSHPASS ssh -v $SSHUSER@$SSHHOST:crosswalk/build/deploy.sh

