sudo: required
dist: trusty
language: php

addons:
  sources:
    - sourceline: 'deb http://ppa.launchpad.net/scribus/ppa/ubuntu trusty main/debug'
  apt:
    packages:
      - xvfb
      - scribus-ng      
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start      
script:
  - scribus -v
  - scribus -g -py .travis/to-pdf.py Heft.sla    
