sudo: required
addons:
  sources:
    - sourceline: 'https://launchpad.net/~scribus/+archive/ppa'
  apt:
    packages:
      - scribus-ng
script:
  - scribus -g -py .travis/to-pdf.py Heft.sla
  - ls -l *.pdf
      
