sudo: required
dist: trusty
language: php
addons:
  ssh_known_hosts: vmfds.de
before_install:
- sudo add-apt-repository -y ppa:scribus/ppa
- sudo apt-get -qq update
- sudo apt-get install -y xvfb scribus-ng sshpass rsync
- sudo timedatectl set-timezone Europe/Berlin
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- export TRAVIS_DATE=$(date -u +"%d.%m.%Y, %H:%M Uhr")
- sed -i "s/###VERSION###/$TRAVIS_BRANCH-2.0.$TRAVIS_BUILD_NUMBER vom $TRAVIS_DATE/g" Heft.sla
script:
- sudo cp -R Grafik/Schriftarten /usr/share/fonts/truetype
- sudo fc-cache -f -v
- scribus-ng -g -py .travis/lehrerheft.py -pa verbose  -- Heft.sla
- mv Heft.pdf Lehrerheft-$TRAVIS_BRANCH-2.0.$TRAVIS_BUILD_NUMBER.pdf
- scribus-ng -g -py .travis/schuelerheft.py -pa verbose  -- Heft.sla
- mv Heft.pdf Schuelerheft-$TRAVIS_BRANCH-2.0.$TRAVIS_BUILD_NUMBER.pdf
after_success:
- eval "$(ssh-agent -s)"
- ssh-keyscan $SSHHOST >> ~/.ssh/known_hosts
- sshpass -p $SSHPASS rsync -avz -e "ssh" --progress *.pdf $SSHUSER@$SSHHOST:/home/$SSHUSER/crosswalk/build/
- sshpass -p $SSHPASS ssh $SSHUSER@$SSHHOST '~/crosswalk/build/deploy.sh' 
